#Name: monitoring
services:
  grafana:
    build: '/home/monitoring/grafana'
    container_name: grafana
    ports:
      - "23000:3000"
    restart: always
    volumes:
      - /home/monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "29090:9090"
    restart: always
    volumes:
      - /home/monitoring/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus

networks:
  monitoring: